openapi: 3.0.0
info:
  title: Node.js Sign-up and Verification API
  description: Node.js Express Sequelize MySQL Web API with email Sign Up, verification, authentication and forgot password
  version: 1.0.0

servers:
  - url: http://localhost:443
    description: Local development server
